version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    container_name : rabbit
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    restart: always
    command: mongod 
